[project]
name = "rogo"
version = "0.1.1"
description='A tool for test-driven teaching.'
dependencies = [
  "jwt ~= 1.3.1",
  "requests ~= 2.31.0",
  "quart ~= 0.19.4",
]

[project.scripts]
rogo = "rogo.driver:main"

[project.license]
file = "LICENSE"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
